const customerData = [
  {
    id: 0,
    name: 'John Doe',
    birthDate: '2018/01/01',
    status: 'Active',
    phone: '837462901',
    email: 'mm.m@gmail.com',
    home: 'Praha',
    nationality: 'Czech',
    language: 'Czech',
    company: 'Dell',
    position: 'Programer',
    car: 'Mercedes',
    create: '11.12.2019',
    attachment: ''
  },
  {
    id: 1,
    name: 'Samppa Nori',
    birthDate: '2018/01/01',
    status: 'Active',
    phone: '',
    email: '',
    home: '',
    nationality: '',
    language: '',
    company: '',
    position: '',
    car: '',
    create: '',
    attachment: ''
  },
  {
    id: 2,
    name: 'Estavan Lykos',
    birthDate: '2018/02/01',
    status: 'Active',
    phone: '',
    email: '',
    home: '',
    nationality: '',
    language: '',
    company: '',
    position: '',
    car: '',
    create: '',
    attachment: ''
  },
  {
    id: 3,
    name: 'Chetan Mohamed',
    birthDate: '2018/02/01',
    status: 'Inactive',
    phone: '',
    email: '',
    home: '',
    nationality: '',
    language: '',
    company: '',
    position: '',
    car: '',
    create: '',
    attachment: ''
  },
  {
    id: 4,
    name: 'Derick Maximinus',
    birthDate: '2018/03/01',
    status: 'Active',
    phone: '',
    email: '',
    home: '',
    nationality: '',
    language: '',
    company: '',
    position: '',
    car: '',
    create: '',
    attachment: ''
  },
  {
    id: 5,
    name: 'Friderik Dávid',
    birthDate: '2018/01/21',
    status: 'Active',
    phone: '',
    email: '',
    home: '',
    nationality: '',
    language: '',
    company: '',
    position: '',
    car: '',
    create: '',
    attachment: ''
  },
  {
    id: 6,
    name: 'Yiorgos Avraamu',
    birthDate: '2018/01/01',
    status: 'Active',
    phone: '',
    email: '',
    home: '',
    nationality: '',
    language: '',
    company: '',
    position: '',
    car: '',
    create: '',
    attachment: ''
  },
  {
    id: 7,
    name: 'Avram Tarasios',
    birthDate: '2018/02/01',
    status: 'Banned',
    phone: '',
    email: '',
    home: '',
    nationality: '',
    language: '',
    company: '',
    position: '',
    car: '',
    create: '',
    attachment: ''
  },
  {
    id: 8,
    name: 'Quintin Ed',
    birthDate: '2018/02/01',
    status: 'Inactive',
    phone: '',
    email: '',
    home: '',
    nationality: '',
    language: '',
    company: '',
    position: '',
    car: '',
    create: '',
    attachment: ''
  },
  {
    id: 9,
    name: 'Enéas Kwadwo',
    birthDate: '2018/03/01',
    status: 'Active',
    phone: '',
    email: '',
    home: '',
    nationality: '',
    language: '',
    company: '',
    position: '',
    car: '',
    create: '',
    attachment: ''
  },
  {
    id: 10,
    name: 'Agapetus Tadeáš',
    birthDate: '2018/01/21',
    status: 'Active',
    phone: '',
    email: '',
    home: '',
    nationality: '',
    language: '',
    company: '',
    position: '',
    car: '',
    create: '',
    attachment: ''
  },
]

export default customerData
